
project_id = "sxsytphycibqcprqjzki"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[[fetch.endpoints]]
url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent"
