// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxsytphycibqcprqjzki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4c3l0cGh5Y2licWNwcnFqemtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTg1MzIsImV4cCI6MjA1NzM3NDUzMn0.GYMLgaFQpzdYMr7_DKHvFfQYUPW-c8TzUruN1mkbhRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);